🧬 生信练习题：RNA-seq 样本表达量分析与分组统计
你有一个 RNA-seq 表达量数据结构 rna_batches，表示多个批次中不同样本的基因表达量（TPM）。请你编写程序完成以下任务：

```python
rna_batches = {
    "Batch_1": {
        "Sample_A": [12.5, 15.2, 13.8, 14.1],
        "Sample_B": [5.1, 4.8, 5.3, 5.0],
        "Sample_C": [20.0, 22.1, 21.5, 19.8],
        "Sample_D": [8.5, 9.0, 8.8, 9.2]
    },
    "Batch_2": {
        "Sample_E": [30.5, 32.1, 31.8, 33.0],
        "Sample_F": [10.0, 9.8, 10.2, 10.1],
        "Sample_G": [2.5, 2.8, 2.6, 2.7],
        "Sample_H": [18.0, 17.5, 18.2, 17.8]
    }
}
```

---
🎯 要求：
计算每个样本的平均表达量（mean）和标准差（std）

根据平均表达量分组：

≥ 25："high_expression"

≥ 15："medium_expression"

≥ 5："low_expression"

否则："very_low"

在每个 batch 内按平均表达量从高到低排序并分配排名

统计每个 batch 中各表达等级的样本数量和平均表达量

找出每个 batch 中表达量最低的样本

---
✅ 输出结构示例：
```python
rna_info = {
    "Batch_1": {
        "samples": {
            "Sample_A": {"values": [...], "mean": ..., "std": ..., "group": ..., "rank": ...},
            ...
        },
        "group_summary": {
            "high_expression": {"count": ..., "avg_mean": ...},
            "low_expression": {...},
            ...
        },
        "lowest_sample": "Sample_B"
    },
    ...
}
```

In [31]:
rna_batches = {
    "Batch_1": {
        "Sample_A": [12.5, 15.2, 13.8, 14.1],
        "Sample_B": [5.1, 4.8, 5.3, 5.0],
        "Sample_C": [20.0, 22.1, 21.5, 19.8],
        "Sample_D": [8.5, 9.0, 8.8, 9.2]
    },
    "Batch_2": {
        "Sample_E": [30.5, 32.1, 31.8, 33.0],
        "Sample_F": [10.0, 9.8, 10.2, 10.1],
        "Sample_G": [2.5, 2.8, 2.6, 2.7],
        "Sample_H": [18.0, 17.5, 18.2, 17.8]
    }
}
rna_batch_info= {}
for batch,sample_info in rna_batches.items():
    Samples = {}
    group_summary = {}
    mean_list = []
    for sample_name,values in sample_info.items():
        mean = sum(values)/len(values)
        mean_list.append((sample_name,mean))
        if all(v >= 25 for v in values):
            quality = "high_expression"
        elif all(v >= 15 for v in values):
            quality = "medium_expression"
        elif all(v >= 10 for v in values):
            quality = "low_expression"
        else:
            quality = "very low"
        Samples[sample_name] = {'quality':quality,'mean':mean}
    
    for i in range(len(mean_list)):
        for j in range(len(mean_list)-i-1):
            if mean_list[j][1] < mean_list[j+1][1]:
                mean_list[j],mean_list[j+1] = mean_list[j+1],mean_list[j]
    rank = 1
    for sample_name,_ in mean_list:
        Samples[sample_name]['rank'] = rank
        rank += 1
    
    for sample_name,details in Samples.items():
        q = details['quality']
        mean = details['mean']
        if q not in group_summary:
            group_summary[q] = {'counts':0,'mean':mean}
        group_summary[q]['counts'] += 1
        avg_mean = mean/group_summary[q]['counts']
        group_summary[q]['avg_mean']=avg_mean
    rna_batch_info[batch]={'Samples':Samples,'group_summary':group_summary}
print(Samples) 
print(mean_list)
print(group_summary)
print(rna_batch_info)

{'Sample_E': {'quality': 'high_expression', 'mean': 31.85, 'rank': 1}, 'Sample_F': {'quality': 'very low', 'mean': 10.025, 'rank': 3}, 'Sample_G': {'quality': 'very low', 'mean': 2.65, 'rank': 4}, 'Sample_H': {'quality': 'medium_expression', 'mean': 17.875, 'rank': 2}}
[('Sample_E', 31.85), ('Sample_H', 17.875), ('Sample_F', 10.025), ('Sample_G', 2.65)]
{'high_expression': {'counts': 1, 'mean': 31.85, 'avg_mean': 31.85}, 'very low': {'counts': 2, 'mean': 10.025, 'avg_mean': 1.325}, 'medium_expression': {'counts': 1, 'mean': 17.875, 'avg_mean': 17.875}}
{'Batch_1': {'Samples': {'Sample_A': {'quality': 'low_expression', 'mean': 13.9, 'rank': 2}, 'Sample_B': {'quality': 'very low', 'mean': 5.05, 'rank': 4}, 'Sample_C': {'quality': 'medium_expression', 'mean': 20.85, 'rank': 1}, 'Sample_D': {'quality': 'very low', 'mean': 8.875, 'rank': 3}}, 'group_summary': {'low_expression': {'counts': 1, 'mean': 13.9, 'avg_mean': 13.9}, 'very low': {'counts': 2, 'mean': 5.05, 'avg_mean': 4.4375}, 'mediu

In [1]:
rna_batches = {
    "Batch_1": {
        "Sample_A": [12.5, 15.2, 13.8, 14.1],
        "Sample_B": [5.1, 4.8, 5.3, 5.0],
        "Sample_C": [20.0, 22.1, 21.5, 19.8],
        "Sample_D": [8.5, 9.0, 8.8, 9.2]
    },
    "Batch_2": {
        "Sample_E": [30.5, 32.1, 31.8, 33.0],
        "Sample_F": [10.0, 9.8, 10.2, 10.1],
        "Sample_G": [2.5, 2.8, 2.6, 2.7],
        "Sample_H": [18.0, 17.5, 18.2, 17.8]
    }
}
rna_batch_info= {}
for batch,sample_info in rna_batches.items():
    Samples = {}
    group_summary = {}
    mean_list = []
    for sample_name,values in sample_info.items():
        mean = sum(values)/len(values)
        mean_list.append((sample_name,mean))
        if all(v >= 25 for v in values):
            label = "high_expression"
        elif all(v >= 15 for v in values):
            label = "medium_expression"
        elif all(v >= 10 for v in values):
            label = "low_expression"
        else:
            label = "very low"
        Samples[sample_name] = {'label':label,'mean':mean}
    
    for i in range(len(mean_list)):
        for j in range(len(mean_list)-i-1):
            if mean_list[j][1] < mean_list[j+1][1]:
                mean_list[j],mean_list[j+1] = mean_list[j+1],mean_list[j]
    rank = 1
    for sample_name,_ in mean_list:
        Samples[sample_name]['rank'] = rank
        rank += 1
    
    for sample_name,details in Samples.items():
        q = details['label']
        mean = details['mean']
        if q not in group_summary:
            group_summary[q] = {'counts':0,'mean':mean}
        group_summary[q]['counts'] += 1
        avg_mean = mean/group_summary[q]['counts']
        group_summary[q]['avg_mean']=avg_mean
    rna_batch_info[batch]={'Samples':Samples,'group_summary':group_summary}
print(Samples) 
print(mean_list)
print(group_summary)
print(rna_batch_info)

{'Sample_E': {'label': 'high_expression', 'mean': 31.85, 'rank': 1}, 'Sample_F': {'label': 'very low', 'mean': 10.025, 'rank': 3}, 'Sample_G': {'label': 'very low', 'mean': 2.65, 'rank': 4}, 'Sample_H': {'label': 'medium_expression', 'mean': 17.875, 'rank': 2}}
[('Sample_E', 31.85), ('Sample_H', 17.875), ('Sample_F', 10.025), ('Sample_G', 2.65)]
{'high_expression': {'counts': 1, 'mean': 31.85, 'avg_mean': 31.85}, 'very low': {'counts': 2, 'mean': 10.025, 'avg_mean': 1.325}, 'medium_expression': {'counts': 1, 'mean': 17.875, 'avg_mean': 17.875}}
{'Batch_1': {'Samples': {'Sample_A': {'label': 'low_expression', 'mean': 13.9, 'rank': 2}, 'Sample_B': {'label': 'very low', 'mean': 5.05, 'rank': 4}, 'Sample_C': {'label': 'medium_expression', 'mean': 20.85, 'rank': 1}, 'Sample_D': {'label': 'very low', 'mean': 8.875, 'rank': 3}}, 'group_summary': {'low_expression': {'counts': 1, 'mean': 13.9, 'avg_mean': 13.9}, 'very low': {'counts': 2, 'mean': 5.05, 'avg_mean': 4.4375}, 'medium_expression': {

In [5]:
training_data = []

for batch_name in rna_batch_info:
    samples = rna_batch_info[batch_name]['Samples']
    for sample_name in samples:
        info = samples[sample_name]
        sample_dict = {
            'sample': sample_name,
            'mean': round(info['mean'], 2),
            'rank': info['rank'],
            'label': info['label']
        }
        training_data.append(sample_dict)


In [14]:
rna_batches = {
    "Batch_1": {
        "Sample_A": [12.5, 15.2, 13.8, 14.1],
        "Sample_B": [5.1, 4.8, 5.3, 5.0],
        "Sample_C": [20.0, 22.1, 21.5, 19.8],
        "Sample_D": [8.5, 9.0, 8.8, 9.2]
    },
    "Batch_2": {
        "Sample_E": [30.5, 32.1, 31.8, 33.0],
        "Sample_F": [10.0, 9.8, 10.2, 10.1],
        "Sample_G": [2.5, 2.8, 2.6, 2.7],
        "Sample_H": [18.0, 17.5, 18.2, 17.8]
    },
    "Batch_3": {
        "Sample_I": [25.0, 24.5, 25.5, 26.0],
        "Sample_J": [14.0, 13.5, 14.2, 13.8],
        "Sample_K": [6.0, 6.5, 6.2, 6.1],
        "Sample_L": [19.5, 20.0, 19.8, 20.2]
    },
    "Batch_4": {
        "Sample_M": [11.0, 11.5, 11.2, 11.3],
        "Sample_N": [3.0, 3.5, 3.2, 3.1],
        "Sample_O": [16.0, 16.5, 16.2, 16.1],
        "Sample_P": [27.0, 28.5, 27.8, 28.2]
    }
}

'''
🧠 任务目标：
对每个样本计算表达标准差（std）

根据 std 值打标签：

std < 0.3 → "stable"

0.3 ≤ std < 1.0 → "moderate"

std ≥ 1.0 → "unstable"

按 std 值降序排序并赋 rank

汇总每个标签的样本数和平均 std

封装为函数：analyze_expression_variability(batch_name, rna_batches)
✅ 练习要求：
使用 statistics.stdev() 或 numpy.std() 计算标准差

不引入全局变量，函数应独立运行

保持结构清晰，变量命名合理

可选：支持多个批次循环调用
'''

batch_info = {}
for batch,sample_info in rna_batches.items():
    Samples = {}
    for Sample_name,values in sample_info.items():
        mean = sum(values)/len(values)
        diff = [(v - mean)**2 for v in values]
        std = (sum(diff)/len(values))**0.5
        if std < 0.3:
            label = 'stable'
        elif 0.3 <= std < 1.0:
            label = 'moderate'
        else:
            label = 'unstable'
        Samples[Sample_name] = {'std':std,'label':label}
    std_list = []
    for Sample_name,details in Samples.items():
        std = details['std']
        std_list.append((Sample_name,std))
    for i in range(len(std_list)):
        for j in range(len(std_list)-i-1):
            if std_list[j][1] < std_list[j+1][1]:
                std_list[j],std_list[j+1] = std_list[j+1],std_list[j]
    rank = 1
    for Sample_name,_ in std_list:
        Samples[Sample_name]['rank'] = rank
        rank += 1
    batch_info['batch'] = {'Samples':Samples}
batch_info

{'batch': {'Samples': {'Sample_M': {'std': 0.18027756377319956,
    'label': 'stable',
    'rank': 4},
   'Sample_N': {'std': 0.18708286933869706, 'label': 'stable', 'rank': 2},
   'Sample_O': {'std': 0.18708286933869686, 'label': 'stable', 'rank': 3},
   'Sample_P': {'std': 0.5629165124598849, 'label': 'moderate', 'rank': 1}}}}

In [15]:
def analyze_rna_batches(rna_batches):
    batch_info = {}
    for batch,sample_info in rna_batches.items():
        Samples = {}
        for Sample_name,values in sample_info.items():
            mean = sum(values)/len(values)
            diff = [(v - mean)**2 for v in values]
            std = (sum(diff)/len(values))**0.5
            if std < 0.3:
                label = 'stable'
            elif 0.3 <= std < 1.0:
                label = 'moderate'
            else:
                label = 'unstable'
            Samples[Sample_name] = {'std':std,'label':label}
            std_list = []
            for Sample_name,details in Samples.items():
                std = details['std']
                std_list.append((Sample_name,std))
            for i in range(len(std_list)):
                for j in range(len(std_list)-i-1):
                    if std_list[j][1] < std_list[j+1][1]:
                        std_list[j],std_list[j+1] = std_list[j+1],std_list[j]
            rank = 1
            for Sample_name,_ in std_list:
                Samples[Sample_name]['rank'] = rank
                rank += 1
            batch_info['batch'] = {'Samples':Samples}
        return batch_info
        

In [49]:
'''
🧠 任务目标：
计算全局均值：每个 batch 的所有表达值的平均值

计算每个样本的偏差值：样本均值与全局均值的绝对差值

根据偏差值打标签：

偏差 < 2 → "aligned"

2 ≤ 偏差 < 5 → "mild_shift"

偏差 ≥ 5 → "strong_shift"

按偏差值降序排序并赋 rank

构造分组统计：每类标签的样本数和平均偏差

封装为函数：analyze_expression_deviation(batch_name, rna_batches)
'''

rna_batches = {
    "Batch_1": {
        "Sample_A": [12.5, 15.2, 13.8, 14.1],
        "Sample_B": [5.1, 4.8, 5.3, 5.0],
        "Sample_C": [20.0, 22.1, 21.5, 19.8],
        "Sample_D": [8.5, 9.0, 8.8, 9.2]
    },
    "Batch_2": {
        "Sample_E": [30.5, 32.1, 31.8, 33.0],
        "Sample_F": [10.0, 9.8, 10.2, 10.1],
        "Sample_G": [2.5, 2.8, 2.6, 2.7],
        "Sample_H": [18.0, 17.5, 18.2, 17.8]
    },
    "Batch_3": {
        "Sample_I": [25.0, 24.5, 25.5, 26.0],
        "Sample_J": [14.0, 13.5, 14.2, 13.8],
        "Sample_K": [6.0, 6.5, 6.2, 6.1],
        "Sample_L": [19.5, 20.0, 19.8, 20.2]
    },
    "Batch_4": {
        "Sample_M": [11.0, 11.5, 11.2, 11.3],
        "Sample_N": [3.0, 3.5, 3.2, 3.1],
        "Sample_O": [16.0, 16.5, 16.2, 16.1],
        "Sample_P": [27.0, 28.5, 27.8, 28.2]
    }
}

batch_info = {}

for batch, Samples_info in rna_batches.items():
    Samples = {}
    mean_list = []

    # Step 1: 计算每个样本均值
    for Sample_name, values in Samples_info.items():
        sample_mean = sum(values) / len(values)
        mean_list.append((Sample_name, sample_mean))

    # Step 2: 计算 batch 全局均值
    mean_list_values = [v for _, v in mean_list]
    batch_mean = sum(mean_list_values) / len(mean_list_values)

    # Step 3: 构造 Samples 和 sample_diff_list
    sample_diff_list = []
    for Sample_name, sample_mean in mean_list:
        sample_diff = batch_mean - sample_mean
        abs_diff = abs(sample_diff)

        if abs_diff < 2:
            label = "aligned"
        elif 2 <= abs_diff <= 5:
            label = "mild_shift"
        else:
            label = "strong_shift"

        Samples[Sample_name] = {
            'sample_mean': sample_mean,
            'sample_diff': sample_diff,
            'label': label
        }
        sample_diff_list.append((Sample_name, abs_diff))



    group_summary = {}

    for sample_name, details in Samples.items():
        label = details['label']
        deviation = abs(details['sample_diff'])  # 用绝对偏差值统计

        if label not in group_summary:
            group_summary[label] = {'counts': 0, 'deviation_sum': 0}

        group_summary[label]['counts'] += 1
        group_summary[label]['deviation_sum'] += deviation

    # 计算平均偏差
    for label in group_summary:
        count = group_summary[label]['counts']
        total = group_summary[label]['deviation_sum']
        group_summary[label]['avg_deviation'] = total / count
        del group_summary[label]['deviation_sum']


    # Step 4: 排序并赋 rank
    sample_diff_list.sort(key=lambda x: x[1], reverse=True)
    rank = 1
    for Sample_name, _ in sample_diff_list:
        Samples[Sample_name]['rank'] = rank
        rank += 1

    # Step 5: 保存结果
    batch_info[batch] = {'Samples': Samples,
                        'group_summary': group_summary }

print(batch_info)


{'Batch_1': {'Samples': {'Sample_A': {'sample_mean': 13.9, 'sample_diff': -1.7312499999999993, 'label': 'aligned', 'rank': 4}, 'Sample_B': {'sample_mean': 5.05, 'sample_diff': 7.118750000000001, 'label': 'strong_shift', 'rank': 2}, 'Sample_C': {'sample_mean': 20.85, 'sample_diff': -8.68125, 'label': 'strong_shift', 'rank': 1}, 'Sample_D': {'sample_mean': 8.875, 'sample_diff': 3.293750000000001, 'label': 'mild_shift', 'rank': 3}}, 'group_summary': {'aligned': {'counts': 1, 'avg_deviation': 1.7312499999999993}, 'strong_shift': {'counts': 2, 'avg_deviation': 7.9}, 'mild_shift': {'counts': 1, 'avg_deviation': 3.293750000000001}}}, 'Batch_2': {'Samples': {'Sample_E': {'sample_mean': 31.85, 'sample_diff': -16.25, 'label': 'strong_shift', 'rank': 1}, 'Sample_F': {'sample_mean': 10.025, 'sample_diff': 5.574999999999999, 'label': 'strong_shift', 'rank': 3}, 'Sample_G': {'sample_mean': 2.65, 'sample_diff': 12.95, 'label': 'strong_shift', 'rank': 2}, 'Sample_H': {'sample_mean': 17.875, 'sample_di

In [51]:
def analyze_group_summary(Samples):
    group_summary = {}

    for sample_name, details in Samples.items():
        label = details['label']
        deviation = abs(details['sample_diff'])  # 用绝对偏差值统计

        if label not in group_summary:
            group_summary[label] = {'counts': 0, 'deviation_sum': 0}

        group_summary[label]['counts'] += 1
        group_summary[label]['deviation_sum'] += deviation
    return group_summary

In [1]:
import numpy as np
import pandas as pd

data = {
    "Genotype": ["AA", "AG", "GG", "AG", "AA"],
    "Tissue":   ["Liver", "Kidney", "Heart", "Brain", "Liver"],
    "Age":      [45, 50, 60, 40, 55],
    "Expression": [5.2, 6.1, 7.3, 4.8, 6.5]
}
df = pd.DataFrame(data)

df_encoded = pd.get_dummies(df, columns=["Genotype","Tissue"], drop_first=False)
feature_cols = [c for c in df_encoded.columns if c != "Expression"]
X = df_encoded[feature_cols].values.astype(float)
X = np.hstack([np.ones((X.shape[0],1)), X])   # 加截距
y = df_encoded["Expression"].values.reshape(-1,1)

print("feature_names:", ["Intercept"] + feature_cols) 
print("X.shape, y.shape:", X.shape, y.shape)
print("X:\n", X)
print("y:\n", y.flatten())


feature_names: ['Intercept', 'Age', 'Genotype_AA', 'Genotype_AG', 'Genotype_GG', 'Tissue_Brain', 'Tissue_Heart', 'Tissue_Kidney', 'Tissue_Liver']
X.shape, y.shape: (5, 9) (5, 1)
X:
 [[ 1. 45.  1.  0.  0.  0.  0.  0.  1.]
 [ 1. 50.  0.  1.  0.  0.  0.  1.  0.]
 [ 1. 60.  0.  0.  1.  0.  1.  0.  0.]
 [ 1. 40.  0.  1.  0.  1.  0.  0.  0.]
 [ 1. 55.  1.  0.  0.  0.  0.  0.  1.]]
y:
 [5.2 6.1 7.3 4.8 6.5]


In [2]:
df_encoded_base = pd.get_dummies(df, columns=["Genotype","Tissue"], drop_first=True)
feature_cols2 = [c for c in df_encoded_base.columns if c != "Expression"]
X2 = df_encoded_base[feature_cols2].values.astype(float)
X2 = np.hstack([np.ones((X2.shape[0],1)), X2])
y2 = df_encoded_base["Expression"].values.reshape(-1,1)

print("feature_names (drop_first=True):", ["Intercept"] + feature_cols2)
print("X2.shape:", X2.shape)
print("X2:\n", X2)


feature_names (drop_first=True): ['Intercept', 'Age', 'Genotype_AG', 'Genotype_GG', 'Tissue_Heart', 'Tissue_Kidney', 'Tissue_Liver']
X2.shape: (5, 7)
X2:
 [[ 1. 45.  0.  0.  0.  0.  1.]
 [ 1. 50.  1.  0.  0.  1.  0.]
 [ 1. 60.  0.  1.  1.  0.  0.]
 [ 1. 40.  1.  0.  0.  0.  0.]
 [ 1. 55.  0.  0.  0.  0.  1.]]


In [3]:
df_enc = pd.get_dummies(df, columns=["Genotype","Tissue"], drop_first=False)
# 标准化 Age
age_mean = df_enc["Age"].mean()
age_std  = df_enc["Age"].std(ddof=0)
df_enc["Age_scaled"] = (df_enc["Age"] - age_mean) / age_std

# 用 Age_scaled 构建 X
feature_cols3 = [c for c in df_enc.columns if c not in ("Expression","Age")]
X3 = df_enc[feature_cols3].values.astype(float)
X3 = np.hstack([np.ones((X3.shape[0],1)), X3])
y3 = df_enc["Expression"].values.reshape(-1,1)

print("feature_names (with Age_scaled):", ["Intercept"] + feature_cols3)
print("X3.shape:", X3.shape)
print("first 3 rows of X3:\n", X3[:3])


feature_names (with Age_scaled): ['Intercept', 'Genotype_AA', 'Genotype_AG', 'Genotype_GG', 'Tissue_Brain', 'Tissue_Heart', 'Tissue_Kidney', 'Tissue_Liver', 'Age_scaled']
X3.shape: (5, 9)
first 3 rows of X3:
 [[ 1.          1.          0.          0.          0.          0.
   0.          1.         -0.70710678]
 [ 1.          0.          1.          0.          0.          0.
   1.          0.          0.        ]
 [ 1.          0.          0.          1.          0.          1.
   0.          0.          1.41421356]]


In [3]:
def analyz_rna_batch(rna_batches):
    batch_info = {}
    for Batch,Samples_info in rna_batches.items():
        Sample_details = {}
        for Sample,values in Samples_info.items():
            Sample_mean = sum(values) / len(values)
            Sample_diff_square = [(v - Sample_mean)**2 for v in values]
            Sample_var = sum(Sample_diff_square) / len(Sample_diff_square)
            Sample_std = round(Sample_var**0.5,3)
            Sample_CV = round(Sample_std / Sample_mean,3)
            if Sample_CV < 0.05 :
                label = "highly_consistent"
            elif  0.05 <= Sample_CV <0.15 :
                label = "moderate_consistent"
            else :
                label = "variable"
            Sample_details[Sample] = {'Sample_std':Sample_std,'Sample_mean':Sample_mean,
                                    'Sample_CV': Sample_CV,'label':label}
    
        CV_list = []
        for Sample , details in Sample_details.items():
            Sample_CV = details['Sample_CV']
            CV_list.append((Sample,Sample_CV))

        for i in range(len(CV_list)):
            for j in range(len(CV_list)-i-1):
                if CV_list[j][1] < CV_list[j+1][1]:
                    CV_list[j],CV_list[j+1] = CV_list[j],CV_list[j+1]
        
        rank = 1
        for Sample,_ in CV_list:
            Sample_details[Sample]['rank'] = rank 
            rank += 1
    
        batch_quality_summary = {}
        for Sample ,details in Sample_details.items():
            label = details['label']
            deviation = details['Sample_CV']
            if label not in batch_quality_summary:
                batch_quality_summary[label] = {'counts': 0,'deviation_sum':0}
            batch_quality_summary[label]['counts'] += 1
            batch_quality_summary[label]['deviation_sum'] += deviation

        # 计算平均偏差
        for label in batch_quality_summary:
            count = batch_quality_summary[label]['counts']
            total = batch_quality_summary[label]['deviation_sum']
            batch_quality_summary[label]['avg_deviation'] = total / count
            del batch_quality_summary[label]['deviation_sum']
        batch_info[Batch] = {
            "Samples": Sample_details,
            "GroupSummary": batch_quality_summary
        }
        return batch_info

In [18]:
rna_batches_exercise = {
    "Batch_A": {
        "Sample_1": [10.2, 10.5, 10.3, 10.4],
        "Sample_2": [4.0, 4.5, 4.2, 4.3],
        "Sample_3": [18.0, 19.2, 18.8, 17.9],
        "Sample_4": [7.5, 7.8, 7.6, 7.7]
    },
    "Batch_B": {
        "Sample_5": [22.0, 23.5, 22.8, 23.1],
        "Sample_6": [9.0, 9.2, 9.1, 9.3],
        "Sample_7": [3.5, 3.8, 3.6, 3.7],
        "Sample_8": [15.0, 15.5, 15.2, 15.3]
    },
    "Batch_C": {
        "Sample_9": [28.0, 27.5, 28.2, 28.1],
        "Sample_10": [12.0, 12.5, 12.2, 12.3],
        "Sample_11": [5.5, 5.8, 5.6, 5.7],
        "Sample_12": [20.0, 20.5, 20.2, 20.3]
    },
    "Batch_D": {
        "Sample_13": [14.0, 14.5, 14.2, 14.3],
        "Sample_14": [2.0, 2.5, 2.2, 2.3],
        "Sample_15": [17.0, 17.8, 17.5, 17.3],
        "Sample_16": [30.0, 31.2, 30.8, 31.0]
    }
}
for Batch, Sample_info in rna_batches_exercise.items():
    Sample_details = {}
    for Sample, values in Sample_info.items():
        mean = sum(values) / len(values)
        var = sum((v - mean) ** 2 for v in values) / len(values)
        std = var ** 0.5
        cv = round(std / mean, 3)

        if cv < 0.05:
            label = "high_consistent"
        elif cv < 0.15:
            label = "moderate_consistent"
        else:
            label = "variable"

        Sample_details[Sample] = {"mean": mean, "std": std, "cv": cv, "label": label}
        for i in range(len(Sample_CV_list)):
            for j in range(len(Sample_CV_list) - i - 1):
                if Sample_CV_list[j][1] < Sample_CV_list[j+1][1]:
                    Sample_CV_list[j],Sample_CV_list[j+1] = Sample_CV_list[j+1],Sample_CV_list[j]
                    

        # 按 CV 排序并加 rank
        sorted_samples = sorted(Sample_details.items(), key=lambda x: x[1]["cv"], reverse=True)
        for rank, (Sample, _) in enumerate(sorted_samples, start=1):
            Sample_details[Sample]["rank"] = rank

        print(f"{Batch}:")
        for s, d in Sample_details.items():
            print(f"  {s}: {d}")

Batch_A:
  Sample_1: {'mean': 10.35, 'std': 0.11180339887498968, 'cv': 0.011, 'label': 'high_consistent', 'rank': 1}
Batch_A:
  Sample_1: {'mean': 10.35, 'std': 0.11180339887498968, 'cv': 0.011, 'label': 'high_consistent', 'rank': 2}
  Sample_2: {'mean': 4.25, 'std': 0.18027756377319945, 'cv': 0.042, 'label': 'high_consistent', 'rank': 1}
Batch_A:
  Sample_1: {'mean': 10.35, 'std': 0.11180339887498968, 'cv': 0.011, 'label': 'high_consistent', 'rank': 3}
  Sample_2: {'mean': 4.25, 'std': 0.18027756377319945, 'cv': 0.042, 'label': 'high_consistent', 'rank': 1}
  Sample_3: {'mean': 18.475, 'std': 0.5448623679425845, 'cv': 0.029, 'label': 'high_consistent', 'rank': 2}
Batch_A:
  Sample_1: {'mean': 10.35, 'std': 0.11180339887498968, 'cv': 0.011, 'label': 'high_consistent', 'rank': 4}
  Sample_2: {'mean': 4.25, 'std': 0.18027756377319945, 'cv': 0.042, 'label': 'high_consistent', 'rank': 1}
  Sample_3: {'mean': 18.475, 'std': 0.5448623679425845, 'cv': 0.029, 'label': 'high_consistent', 'rank'